import Link from "next/link";
import { notFound, permanentRedirect } from "next/navigation";
import { ArticleImage } from "@/components/ArticleImage";
import { CategoryBadge, NewsCard } from "@/components/NewsCard";
import { ShareButtons } from "@/components/ShareButtons";
import { ViewTracker } from "@/components/ViewTracker";
import { TelegramCta } from "@/components/TelegramCta";
import { siteConfig } from "@/config/site";
import { storyLabel } from "@/lib/labels";
import { getArticleBySlug, getPrimarySlug } from "@/lib/queries";
import { absoluteUrl, jsonLdString, newsArticleJsonLd, pageMetadata } from "@/lib/seo";
import { formatDateTime, safe, truncate } from "@/lib/utils";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const a = await safe(() => getArticleBySlug(slug), null);
  if (!a) return { title: "Story not found", robots: { index: false } };
  return {
    ...pageMetadata({
      title: truncate(a.title, 65),
      description: truncate(a.summary, 155),
      path: `/news/${a.slug}`,
      image: a.imageUrl,
      type: "article",
    }),
  };
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const a = await safe(() => getArticleBySlug(slug), null);
  if (!a) {
    const primary = await safe(() => getPrimarySlug(slug), null);
    if (primary) permanentRedirect(`/news/${primary}`);
    notFound();
  }
  const label = storyLabel(a.sourceCount);
  const url = absoluteUrl(`/news/${a.slug}`);
  const others = a.reports.filter((r) => r.sourceName !== a.sourceName);

  return (
    <article className="container-page max-w-4xl py-8">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLdString(newsArticleJsonLd(a)) }} />
      <ViewTracker id={a.id} />

      <nav aria-label="Breadcrumb" className="mb-3 text-xs text-muted">
        <Link href="/" className="hover:text-brand">Home</Link> / <Link href={`/category/${a.category}`} className="hover:text-brand">{a.categoryName}</Link>
      </nav>

      <div className="flex flex-wrap items-center gap-2">
        <CategoryBadge slug={a.category} name={a.categoryName} />
        <span className={`rounded px-2 py-0.5 text-[11px] font-semibold ${label.tone === "multi" ? "bg-emerald-500/15 text-emerald-700 dark:text-emerald-400" : "bg-amber-500/15 text-amber-700 dark:text-amber-400"}`}>{label.text}</span>
      </div>

      <h1 className="mt-3 font-serif text-3xl font-extrabold leading-tight sm:text-4xl">{a.title}</h1>
      <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-sm text-muted">
        <span>Published <time dateTime={a.publishedAt}>{formatDateTime(a.publishedAt)}</time></span>
        {new Date(a.updatedAt).getTime() - new Date(a.fetchedAt).getTime() > 60_000 && <span>Updated <time dateTime={a.updatedAt}>{formatDateTime(a.updatedAt)}</time></span>}
        <span>Source: <a href={a.sourceUrl} target="_blank" rel="noopener noreferrer nofollow" className="font-semibold text-ink hover:text-brand">{a.sourceName}</a></span>
        {a.author && <span>By {a.author}</span>}
        <span>{a.readingTime} min read</span>
      </div>

      <div className="relative mt-5 aspect-[16/9] overflow-hidden rounded-2xl">
        <ArticleImage src={a.imageUrl} alt={a.originalTitle} category={a.category} priority sizes="(min-width:1024px) 896px, 100vw" />
      </div>
      {a.imageUrl && <p className="mt-1 text-xs text-muted">Image provided via the publisher&apos;s feed · © {a.sourceName}</p>}

      <section className="card mt-6 p-5 sm:p-6" aria-labelledby="sum-h">
        <h2 id="sum-h" className="flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-brand">
          {a.aiProcessed ? "AI-generated summary" : "Summary"}
        </h2>
        <p className="mt-3 font-serif text-lg leading-relaxed">{a.summary}</p>
        {a.keyPoints.length > 0 && (
          <>
            <h3 className="mt-5 text-sm font-bold uppercase tracking-wider text-muted">Key points</h3>
            <ul className="mt-2 list-disc space-y-1.5 pl-5">{a.keyPoints.map((k, i) => <li key={i}>{k}</li>)}</ul>
          </>
        )}
        <p className="mt-5 border-t border-line pt-3 text-xs text-muted">
          {a.aiProcessed ? "This summary was generated by AI from the publisher's headline and excerpt and may contain errors. " : "This summary is extracted from the publisher's feed excerpt. "}
          It is not the original article. Original reporting © {a.sourceName}.
        </p>
        <a href={a.sourceUrl} target="_blank" rel="noopener noreferrer nofollow" className="btn-brand mt-4">Read Original Article ↗</a>
      </section>

      {a.tags.length > 0 && (
        <div className="mt-5 flex flex-wrap gap-2" aria-label="Tags">
          {a.tags.map((t) => <Link key={t.slug} href={`/search?q=${encodeURIComponent(t.name)}`} className="chip">#{t.name}</Link>)}
        </div>
      )}

      <div className="mt-6 border-y border-line py-4"><ShareButtons url={url} title={a.title} /></div>

      {others.length > 0 && (
        <section className="mt-8" aria-labelledby="cov-h">
          <h2 id="cov-h" className="section-title text-xl">{label.text}</h2>
          <p className="text-sm text-muted">Other outlets that reported this story. We link to each publisher&apos;s own report.</p>
          <ul className="mt-3 divide-y divide-line rounded-xl border border-line bg-surface">
            {a.reports.map((r) => (
              <li key={r.id} className="flex flex-col gap-1 p-3 sm:flex-row sm:items-center sm:justify-between">
                <span className="font-medium">{r.title}</span>
                <a href={r.sourceUrl} target="_blank" rel="noopener noreferrer nofollow" className="shrink-0 text-sm font-semibold text-brand hover:underline">{r.sourceName} ↗</a>
              </li>
            ))}
          </ul>
        </section>
      )}

      {a.related.length > 0 && (
        <section className="mt-10" aria-labelledby="rel-h">
          <h2 id="rel-h" className="section-title text-xl">More in {a.categoryName}</h2>
          <div className="mt-3 grid gap-4 sm:grid-cols-2">{a.related.slice(0, 4).map((r) => <NewsCard key={r.id} a={r} />)}</div>
        </section>
      )}

      <div className="mt-10"><TelegramCta url={siteConfig.social.telegram} /></div>
    </article>
  );
}
